server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${sjdddd.datasource.driver-class-name}
    url: jdbc:mysql://${sjdddd.datasource.host}:${sjdddd.datasource.port}/${sjdddd.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sjdddd.datasource.username}
    password: ${sjdddd.datasource.password}
  application:
    name: sjdddd

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.sjdddd.controller


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sjdddd.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sjdddd:
        mapper: debug
        service: info
        controller: info

sjdddd:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: sjdddd
    # 设置jwt过期时间
    user-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    user-token-name: token
