version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: shenjiadong1010
      MYSQL_DATABASE: gym-management

  gym-server:
    image: gym-server:latest
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
